### Default ###
management:
  endpoint.health.probes.enabled: true
  endpoints.web.base-path: "${MANAGEMENT_PATH:/hyd}"

---

### Production ###
spring.config.activate.on-profile: production

management:
  endpoints:
    access.default: none
    web.exposure.include:
      - info
      - health
    jmx.exposure.include:
      - info
      - health
  # For more endpoints, see: https://docs.spring.io/spring-boot/reference/actuator/endpoints.html
  endpoint:
    health:
      show-details: never
      access: read_only
    info:
      access: read_only

---

### Development ###
spring.config.activate.on-profile: development

management:
  endpoint:
    health.show-details: always
  endpoints:
    web.exposure.include: "*"
